# Language
language: java

# Version (dependencies)
jdk:
  - oraclejdk9
  
# Mave dependencies (required by Travis CI) 
./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# Buil project with maven
./mvnw test -B
